spring:
  main:
    allow-bean-definition-overriding : true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL:jdbc:mysql://localhost:3306/svap}
    username: ${USERNAME:root}
    password: ${PASSWORD:070211}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  redis:
    port: 6379
    host: 127.0.0.1

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dfhasjkdfhayffhdtyhdhydshghjkdfaskverafter}
  access-exp: ${JWT_ACCESS_EXP:10000}
  refresh-exp: ${JWT_REFRESH_EXP:604800}


logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS-KEY:AKIA472XLIA4MZWDJ2YB}      # AWS IAM AccessKey 적기
      secretKey: ${SECRET-KEY:r21g2LMb65thGTlzJOxgdneVp/KFXsQG2VudNJkP}   # AWS IAM SecretKey 적기
    s3:
      bucket: ${BUCKET:kangsunbucket}
    region:
      static: ${STATIC:ap-northeast-2}
  stack:
    auto: false